table! {
    /// Representation of the `btc_usdt` table.
    ///
    /// (Automatically generated by Diesel.)
    btc_usdt (id) {
        /// The `id` column of the `btc_usdt` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `date` column of the `btc_usdt` table.
        ///
        /// Its SQL type is `Time`.
        ///
        /// (Automatically generated by Diesel.)
        date -> Time,
        /// The `open` column of the `btc_usdt` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        open -> Numeric,
        /// The `high` column of the `btc_usdt` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        high -> Numeric,
        /// The `low` column of the `btc_usdt` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        low -> Numeric,
        /// The `close` column of the `btc_usdt` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        close -> Numeric,
        /// The `volume` column of the `btc_usdt` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        volume -> Numeric,
    }
}
