table! {
    /// Representation of the `usdt_btc` table.
    ///
    /// (Automatically generated by Diesel.)
    usdt_btc (id) {
        /// The `id` column of the `usdt_btc` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `date` column of the `usdt_btc` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        date -> Timestamp,
        /// The `open` column of the `usdt_btc` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        open -> Float8,
        /// The `high` column of the `usdt_btc` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        high -> Float8,
        /// The `low` column of the `usdt_btc` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        low -> Float8,
        /// The `close` column of the `usdt_btc` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        close -> Float8,
        /// The `volume` column of the `usdt_btc` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        volume -> Float8,
    }
}
